# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20170715_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='imie',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='nazwisko',
        ),
        migrations.AddField(
            model_name='author',
            name='drugie_imie',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
