# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170715_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('is_a_member', models.BooleanField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='imie',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='nazwisko',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='drugie_imie',
            new_name='second_name',
        ),
    ]
