# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_orderstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderStatus',
            new_name='order',
        ),
    ]
