# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20170718_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('due', models.DateField()),
                ('overdue', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user')),
            ],
        ),
    ]
