# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_orderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('topic', models.CharField(max_length=100)),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(max_length=40)),
                ('article', models.TextField()),
            ],
        ),
    ]
